import { createHmac } from 'node:crypto';
import { describe, expect, it, vi } from 'vitest';

const {
  MAX_ATTEMPTS,
  backoffMs,
  classifyFailure,
  classifyStatus,
  nextStep,
} = await import('../dist/b2b-webhooks/webhook-retry-policy.js');
const {
  decryptSecret,
  encryptSecret,
  masterKey,
  newWebhookSecret,
  secretStatus,
  signWebhook,
  signedMessage,
} = await import('../dist/b2b-webhooks/webhook-secret.js');
const {
  attemptWebhookDelivery,
  webhookBody,
  SIGNATURE_HEADER,
  TIMESTAMP_HEADER,
  EVENT_ID_HEADER,
} = await import('../dist/b2b-webhooks/webhook-transport.js');

const KEY_HEX = 'a'.repeat(64);
const key = masterKey(KEY_HEX);
const at = new Date('2026-09-26T12:00:00.000Z');

const event = {
  id: '9a1f0c7e-2222-4000-8000-000000000001',
  type: 'DELIVERY_COMPLETED' as const,
  occurredAt: new Date('2026-09-26T11:30:00.000Z'),
  payload: {
    publicId: 'MDR-000777',
    externalReference: 'ORDER-99',
    status: 'DELIVERED',
    execution: { mode: 'PROVIDER' },
    requestedAt: '2026-09-26T11:00:00.000Z',
    deliveredAt: '2026-09-26T11:30:00.000Z',
    cancelledAt: null,
  },
};

describe('V1.12-D retry policy', () => {
  it('spreads five attempts over a curve that is stated once, in code', () => {
    expect(MAX_ATTEMPTS).toBe(5);
    expect([1, 2, 3, 4].map(backoffMs)).toEqual([
      60_000,
      300_000,
      900_000,
      3_600_000,
    ]);
    expect(backoffMs(5)).toBeNull();
  });

  it('walks the whole schedule without waiting an hour for it', () => {
    let now = at;
    const schedule: string[] = [];
    for (let made = 1; made <= MAX_ATTEMPTS; made += 1) {
      const step = nextStep('RETRYABLE', made, now);
      schedule.push(
        step.state === 'PENDING'
          ? `${(step.nextAttemptAt.getTime() - now.getTime()) / 60000}m`
          : step.state,
      );
      if (step.state === 'PENDING') now = step.nextAttemptAt;
    }
    expect(schedule).toEqual(['1m', '5m', '15m', '60m', 'EXHAUSTED']);
    // The whole curve is 81 minutes from the first attempt.
    expect((now.getTime() - at.getTime()) / 60000).toBe(81);
  });

  it('a success ends it and a terminal answer stops it immediately', () => {
    expect(nextStep('SUCCESS', 1, at)).toEqual({ state: 'DELIVERED' });
    expect(nextStep('TERMINAL', 1, at)).toEqual({ state: 'EXHAUSTED' });
  });

  it('retries what could work later and refuses to hammer what cannot', () => {
    const verdicts = Object.fromEntries(
      [
        200, 201, 202, 204, 301, 302, 400, 401, 403, 404, 405, 408, 409, 410,
        422, 425, 429, 451, 500, 502, 503, 504,
      ].map((s) => [s, classifyStatus(s)]),
    );
    expect(verdicts).toEqual({
      200: 'SUCCESS',
      201: 'SUCCESS',
      202: 'SUCCESS',
      204: 'SUCCESS',
      301: 'TERMINAL',
      302: 'TERMINAL',
      400: 'TERMINAL',
      401: 'TERMINAL',
      403: 'TERMINAL',
      404: 'TERMINAL',
      405: 'TERMINAL',
      408: 'RETRYABLE',
      // Deliberate: the deduplication contract tells a consumer to reject an eventId it already
      // processed, and a conflict is how it says so. Retrying would punish correct receivers.
      409: 'TERMINAL',
      410: 'TERMINAL',
      422: 'TERMINAL',
      425: 'RETRYABLE',
      429: 'RETRYABLE',
      451: 'TERMINAL',
      500: 'RETRYABLE',
      502: 'RETRYABLE',
      503: 'RETRYABLE',
      504: 'RETRYABLE',
    });
  });

  it('retries transient transport failures but not a destination that stopped being valid', () => {
    expect(classifyFailure('TIMEOUT')).toBe('RETRYABLE');
    expect(classifyFailure('NETWORK')).toBe('RETRYABLE');
    expect(classifyFailure('INVALID_ENDPOINT')).toBe('TERMINAL');
  });
});

describe('V1.12-D the signing secret', () => {
  it('is generated by the CSPRNG, not chosen', () => {
    const secrets = new Set(Array.from({ length: 50 }, newWebhookSecret));
    expect(secrets.size).toBe(50);
    for (const secret of secrets) expect(secret.length).toBeGreaterThanOrEqual(43);
  });

  it('round-trips through AES-256-GCM and never stores plaintext', () => {
    const secret = newWebhookSecret();
    const stored = encryptSecret(secret, key);
    expect(stored).not.toContain(secret);
    expect(stored).toMatch(
      /^v1:[A-Za-z0-9_-]{16,}:[A-Za-z0-9_-]{16,}:[A-Za-z0-9_-]{8,}$/,
    );
    expect(decryptSecret(stored, key)).toBe(secret);
  });

  it('encrypts the same secret differently every time', () => {
    const secret = newWebhookSecret();
    expect(encryptSecret(secret, key)).not.toBe(encryptSecret(secret, key));
  });

  it('refuses a tampered ciphertext and a wrong key, without saying which', () => {
    const stored = encryptSecret('hello', key);
    const [v, iv, tag, data] = stored.split(':');
    const flipped = [v, iv, tag, data.slice(0, -2) + 'AA'].join(':');
    const otherKey = masterKey('b'.repeat(64));
    for (const attempt of [
      () => decryptSecret(flipped, key),
      () => decryptSecret(stored, otherKey),
      () => decryptSecret('v2:a:b:c', key),
      () => decryptSecret('not-a-ciphertext', key),
    ])
      expect(attempt).toThrow(/cannot be read/);
  });

  it('rejects a master key that is not 32 bytes', () => {
    for (const bad of [undefined, '', 'short', 'a'.repeat(62)])
      expect(() => masterKey(bad as string)).toThrow(/not configured/);
    // Hex and base64 are both accepted, because operators produce both.
    expect(masterKey(KEY_HEX)).toHaveLength(32);
    expect(masterKey(Buffer.alloc(32, 7).toString('base64'))).toHaveLength(32);
  });

  it('shows only whether a secret exists, never the secret', () => {
    expect(
      secretStatus({ secretCiphertext: encryptSecret('s', key), secretSetAt: at }),
    ).toEqual({ secretConfigured: true, secretSetAt: at });
    expect(
      secretStatus({ secretCiphertext: null, secretSetAt: null }),
    ).toEqual({ secretConfigured: false, secretSetAt: null });
  });
});

describe('V1.12-D the signature contract', () => {
  it('signs timestamp + "." + the exact body, as HMAC-SHA256 in v1=<hex>', () => {
    const body = '{"a":1}';
    expect(signedMessage(1790000000, body)).toBe('1790000000.{"a":1}');
    const expected = createHmac('sha256', 'shhh')
      .update('1790000000.{"a":1}')
      .digest('hex');
    expect(signWebhook('shhh', 1790000000, body)).toBe(`v1=${expected}`);
  });

  it('a receiver verifying the bytes it received gets a match', async () => {
    const secret = newWebhookSecret();
    let seen: { body: string; headers: Record<string, string> } | undefined;
    const fetcher = vi.fn(async (_url: string, init: RequestInit) => {
      seen = {
        body: init.body as string,
        headers: init.headers as Record<string, string>,
      };
      return new Response(null, { status: 200 });
    }) as unknown as typeof fetch;
    await attemptWebhookDelivery('https://example.com/h', event, {
      timeoutMs: 1000,
      policy: { allowInsecureTargets: false },
      secret,
      now: at,
      fetcher,
      resolver: async () => ['93.184.216.34'],
    });
    const timestamp = seen!.headers[TIMESTAMP_HEADER];
    expect(timestamp).toBe(String(Math.floor(at.getTime() / 1000)));
    // Exactly what a consumer would do with the raw request.
    expect(seen!.headers[SIGNATURE_HEADER]).toBe(
      `v1=${createHmac('sha256', secret).update(`${timestamp}.${seen!.body}`).digest('hex')}`,
    );
    expect(JSON.parse(seen!.body)).toEqual(webhookBody(event));
  });

  it('a modified body, timestamp or secret all fail verification', () => {
    const secret = newWebhookSecret();
    const body = JSON.stringify(webhookBody(event));
    const ts = 1790000000;
    const good = signWebhook(secret, ts, body);
    expect(signWebhook(secret, ts, body + ' ')).not.toBe(good);
    expect(signWebhook(secret, ts + 1, body)).not.toBe(good);
    expect(signWebhook(newWebhookSecret(), ts, body)).not.toBe(good);
  });

  it('a retry carries a new timestamp and signature over the very same event', async () => {
    const secret = newWebhookSecret();
    const sent: { body: string; headers: Record<string, string> }[] = [];
    const fetcher = vi.fn(async (_url: string, init: RequestInit) => {
      sent.push({
        body: init.body as string,
        headers: init.headers as Record<string, string>,
      });
      return new Response(null, { status: 500 });
    }) as unknown as typeof fetch;
    const send = (now: Date) =>
      attemptWebhookDelivery('https://example.com/h', event, {
        timeoutMs: 1000,
        policy: { allowInsecureTargets: false },
        secret,
        now,
        fetcher,
        resolver: async () => ['93.184.216.34'],
      });
    await send(at);
    await send(new Date(at.getTime() + 60_000));
    // The event never changes between attempts; only the proof of when it was sent.
    expect(sent[0].body).toBe(sent[1].body);
    expect(sent[0].headers[EVENT_ID_HEADER]).toBe(sent[1].headers[EVENT_ID_HEADER]);
    expect(sent[0].headers[TIMESTAMP_HEADER]).not.toBe(
      sent[1].headers[TIMESTAMP_HEADER],
    );
    expect(sent[0].headers[SIGNATURE_HEADER]).not.toBe(
      sent[1].headers[SIGNATURE_HEADER],
    );
  });

  it('rotating the secret changes what new attempts sign, and nothing else', () => {
    const body = JSON.stringify(webhookBody(event));
    const older = newWebhookSecret();
    const newer = newWebhookSecret();
    const before = signWebhook(older, 1790000000, body);
    const after = signWebhook(newer, 1790000100, body);
    expect(after).not.toBe(before);
    // The old signature is still exactly what it was: history is not rewritten.
    expect(signWebhook(older, 1790000000, body)).toBe(before);
  });

  it('sends no signature header when the endpoint has no secret yet', async () => {
    let headers: Record<string, string> = {};
    const fetcher = vi.fn(async (_url: string, init: RequestInit) => {
      headers = init.headers as Record<string, string>;
      return new Response(null, { status: 200 });
    }) as unknown as typeof fetch;
    await attemptWebhookDelivery('https://example.com/h', event, {
      timeoutMs: 1000,
      policy: { allowInsecureTargets: false },
      now: at,
      fetcher,
      resolver: async () => ['93.184.216.34'],
    });
    expect(headers[SIGNATURE_HEADER]).toBeUndefined();
    expect(headers[TIMESTAMP_HEADER]).toBeDefined();
  });
});
